config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'places#index'

  resources :places do
    resources :accommodations, :except => [:index]
  end
end

app/models/accommodation.rb
class Accommodation < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :housing_type, :presence => true
  validates :guests, :presence => true
  validates :price, :presence => true
  belongs_to :place
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :city, :presence => true
  validates :state, :presence => true
  validates :country, :presence => true
  has_many :accommodations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

   validates :avatar, :attachment_presence => true
   validates_with AttachmentPresenceValidator, :attributes => :avatar
   validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

   after_create :send_welcome_email

   private

   def send_welcome_email
     UserMailer.signup_confirmation(self).deliver_now
   end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]


  def new
    @place = Place.find(params[:place_id])
    @accommodation = @place.accommodations.new
  end

  def create
    @place = Place.find(params[:place_id])
    @accommodation = @place.accommodations.new(accommodations_params)
    if @accommodation.save
      flash[:notice] = "Accommodation saved"
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def show
    @place = Place.find(params[:place_id])
    @accommodation = Accommodation.find(params[:id])
  end

  def edit
    @place = Place.find(params[:place_id])
    @accommodation = Accommodation.find(params[:id])
  end

  def update
    @place = Place.find(params[:place_id])
    @accommodation = Accommodation.find(params[:id])
    if @accommodation.update(accommodations_params)
      flash[:notice] = "Accommodation successfully updated."
      redirect_to places_path(@place)
    else
      render :edit
    end
  end

  def destroy
    @accommodation = Accommodation.find(params[:id])
    @accommodation.destroy
    flash[:notice] = "Accommodation successfully deleted"
    redirect_to places_path(@accommodation.place)
  end
   

private
  def accommodations_params
    params.require(:accommodation).permit(:description, :housing_type, :guests, :price, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar) }
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(places_params)
    if @place.save
      flash[:notice] = "Place saved"
      redirect_to places_path
    else
      render :new
    end
  end

  def show
    @place = Place.find(params[:id])
    @user = current_user
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(places_params)
      flash[:notice] = "Your place has been editied successfully"
      redirect_to places_path
    else
      render :edit
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    flash[:notice] = "Place Deleted"
    redirect_to places_path
  end


private
  def places_params
    params.require(:place).permit(:city, :state, :country)
  end
end

app/controllers/users_controller.rb
class UserController < ActiveRecord::Base

  def create
    @user = User.create( user_params )
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :avatar)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accommodations/_form.html.erb
<%= render "layouts/errors", :object => @accommodation %>

<%= form_for [@place, @accommodation] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :housing_type %>
  <%= f.text_field :housing_type %>
  <%= f.label :guests %>
  <%= f.text_field :guests %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit "Create Accommodation" %>
<% end %>

app/views/accommodations/edit.html.erb
<h1>Edit Accommodations</h1>

<%= render 'form' %>

app/views/accommodations/new.html.erb
<h3>Accommodations for <%= @place.city %></h3>

<%= render 'form' %>

app/views/accommodations/show.html.erb
<h2><%= @accommodation.name %></h2>


  <p><%= @accommodation.name %> $<%= @accommodation.price %></p>
  <p><%= @accommodation.description %></p>
  <p>Type: <%= @accommodation.housing_type %></p>
  <p>Number of Guests: <%= @accommodation.guests %></p>



<p><%= link_to "Edit Accommodation", edit_place_accommodation_path(@place, @accommodation) %></p>
<p><%= link_to "Delete Accommodation", place_accommodation_path(@place, @accommodation), :data => { :confirm => "Are you sure?",
  :method => "delete" } %></p>
  <p><%= link_to "Return to Places", places_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please correct the following errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jazzrnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_nav">
    <% if user_signed_in? %>
    Logged-in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit Profile', edit_user_registration_path %> |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to 'Signup', new_user_registration_path %> |
    <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>



  <div class="row">
    <p>
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </p>
<%= yield %>
  </div>
</div>

</body>
</html>

app/views/places/_form.html.erb
<%= render "layouts/errors", :object => @place %>

<%= form_for @place do |f| %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit "Create Place" %>
<% end %>

app/views/places/edit.html.erb
<h1>Edit Place</h1>

<%= render 'form' %>

app/views/places/index.html.erb
<h2>Welcome to JazzRnB!</h2>

<ul>
  <% @places.each do |p| %>
  <li><%= link_to p.city, place_path(p) %></li>
  <%  end %>
</ul>

<p><%= link_to "Create New Place", new_place_path %></p>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<h2><%= @place.city %></h2>

<% if @place.accommodations.any? %>
  <h3>Available Accommodations:</h3>
    <ul>
      <% @place.accommodations.each do |accommodation| %>
      <li><%= link_to accommodation.name, place_accommodation_path(@place, accommodation) %> $<%= accommodation.price %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no accommodations yet for <%= @place.city %></p>
<% end %>

<p><%= link_to "Add Accommodation", new_place_accommodation_path(@place) %></p>
<p><%= link_to "Edit", edit_place_path(@place) %></p>
<p><%= link_to "Delete", place_path(@place), :data => { :confirm => "Are you sure?",
                                                        :method => "delete" } %></p>
  <p><%= link_to "Return to Places", places_path %></p>



  <p><%= image_tag @user.avatar.url(:thumb) %></p>

app/views/users/edit.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
<%= form.file_field :avatar %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
<%= form.file_field :avatar %>
<% end %>

app/views/users/show.html.erb
<h1>Here are the avatars:</h1>

<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %>